// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-w_ytoYOwBLXXcu9iuZTHLyAeZgLvl4A',
    appId: '1:431970675173:web:09d7acd29d70927165e70c',
    messagingSenderId: '431970675173',
    projectId: 'samples-6668b',
    authDomain: 'samples-6668b.firebaseapp.com',
    storageBucket: 'samples-6668b.appspot.com',
    measurementId: 'G-KM6K95ZYMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxr-xTSOYRkgg6s9mqFzxxoef5Kk-6IAU',
    appId: '1:431970675173:android:635c1cafb040714665e70c',
    messagingSenderId: '431970675173',
    projectId: 'samples-6668b',
    storageBucket: 'samples-6668b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBn_JBF9YbNMEdemiq8LxqQaXwUylHdbw',
    appId: '1:431970675173:ios:41718127c8a8e5f765e70c',
    messagingSenderId: '431970675173',
    projectId: 'samples-6668b',
    storageBucket: 'samples-6668b.appspot.com',
    iosClientId: '431970675173-akcf0jb23599f775rj178374mt464jr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.samples',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBn_JBF9YbNMEdemiq8LxqQaXwUylHdbw',
    appId: '1:431970675173:ios:41718127c8a8e5f765e70c',
    messagingSenderId: '431970675173',
    projectId: 'samples-6668b',
    storageBucket: 'samples-6668b.appspot.com',
    iosClientId: '431970675173-akcf0jb23599f775rj178374mt464jr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.samples',
  );
}
